
redis_cache: ./bench-manage.sh redis-cache
redis_queue: ./bench-manage.sh redis-queue


web: bench serve  --port 8000


socketio: node apps/frappe/socketio.js


watch: bench watch


schedule: bench schedule

worker:  bench worker 1>> logs/worker.log 2>> logs/worker.error.log

